#!/usr/bin/env bash
"""configure Nginx to serve your page from the route
/airbnb-onepage/ and /6-number_odd_or_even/"""
server {
    listen 80;
    location /airbnb-onepage {
        proxy_pass http://127.0.0.1:5000; }
    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001;}
}
